version: "3.8"

services:
  mongo:
    image: mongo
    container_name: balancer_mongo
    command: mongod --config /etc/mongo/mongodb.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./apps/server/configs/mongodb.conf:/etc/mongo/mongodb.conf
      - ./apps/server/configs/mongodb-keyfile:/etc/mongodb-keyfile
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: balancer_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
